name: Build production
on: [push]
  # workflow_dispatch:
  #   inputs:
  #     version:
  #       description: 'Version type'
  #       required: true
  #       type: choice
  #       options: 
  #         - patch
  #         - minor
  #         - major
jobs:
  bump-version:
    runs-on: ubuntu-latest
    outputs:
      version: steps.bump-version.outputs.VERSION
    steps:
      - name: Check out source
        uses: actions/checkout@v2

      - name: Setup Git
        run: |
          git config user.name 'hctr666'
          git config user.email 'hctr666@gmail.com'

      - name: Bump version
        id: bump-version
        run: |
          version=$(echo "$(npm version patch -git-tag-version=false)" | cut -dv -f2)
          git commit -am "Version bump -> $version"
          echo "::set-output name=VERSION::$version"

      - name: Push latest version
        run: |
          echo ${{ steps.bump-version.outputs.VERSION }}

  build:
    runs-on: ubuntu-latest
    needs: [bump-version]
    env:
      FILENAME: "extension@${{ needs.bump-version.outputs.version }}"
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.FILENAME }}
          path: api.zip
